# Generated by Django 2.1.1 on 2020-04-09 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GroupInfo',
            fields=[
                ('groupName', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pendingStatus', models.BooleanField(default='')),
                ('groupName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify_profile.GroupInfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('userName', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='groupmember',
            name='userName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify_profile.UserInfo'),
        ),
        migrations.AddField(
            model_name='following',
            name='followerUserName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followerUserName', to='spotify_profile.UserInfo'),
        ),
        migrations.AddField(
            model_name='following',
            name='followingUserName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followingUserName', to='spotify_profile.UserInfo'),
        ),
    ]
