# Generated by Django 2.1.1 on 2020-04-09 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='followerUserName',
            new_name='userName',
        ),
    ]
