# Generated by Django 2.1.1 on 2020-04-09 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_profile', '0002_auto_20200409_0531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='followingUserName',
            new_name='followingUserInfo',
        ),
        migrations.RenameField(
            model_name='following',
            old_name='userName',
            new_name='userInfo',
        ),
    ]
