# Generated by Django 2.1.1 on 2020-04-09 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_profile', '0004_groupinfo_groupdesc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmember',
            old_name='groupName',
            new_name='groupInfo',
        ),
        migrations.RenameField(
            model_name='groupmember',
            old_name='userName',
            new_name='userInfo',
        ),
    ]
